#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🧪🧪 Testing before commiting 🧪🧪"
# Check Test
yarn test || 
(
    echo '🤡😂❌🤡 Failed Test. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'